version: "3.8"

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432

  user_app:
    build:
      context: ./
      dockerfile: Dockerfile

    enviroment:
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/postgres

    ports:
      - 3000:3000
    depends_upon:
      - postgres          